apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations-server
  template:
    metadata:
      labels:
        app: recommendations-server
    spec:
      containers:
        - name: recommendations-server
          image: public.ecr.aws/r2r2l6v3/ecommerce-recommendations-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations-server-service
spec:
  selector:
    app: recommendations-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP